---
title: "Running methods and computing performance metrics"
author: "Pierre-Luc Germain"
date: "2022/04/11"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(DoubletCollection)
  library(scDblFinder)
})

chordWrapper <- function(x, overkill=TRUE, ...){
  library(Chord)
  if(is.list(x)) x <- x[[1]]
  dbr <- (0.01 * ncol(x)/1000)
  se <- Seurat::CreateSeuratObject(counts=x)
  chord(seu=se, doubletrate=dbr, overkill=TRUE, outname="tmp_chord", ...)
  cs <- read.csv("tmp_chordreal_score.csv", row.names=1)
  unlink("tmp_chord.csv")
  unlink("tmp_chordreal_score.csv")
  cs$chord
}
```


```{r}
datasets <- list.files("datasets", pattern="\\.rds$", full=TRUE)
names(datasets) <- gsub("\\.rds$","",basename(datasets))
methods <- c('Scrublet','cxds','bcds','hybrid','scDblFinder.clusters','scDblFinder.random',
             'DoubletFinder','computeDoubletDensity','Chord')
methods <- methods[-1]
datasets <- lapply(datasets, readRDS)

wrap <- function(x, method){
  switch(method,
      "DoubletFinder"=DoubletCollection:::CallDoubletFinder(x),
      "Scrublet"=DoubletCollection:::CallScrublet(x),
      "scDblFinder"=scDblFinder(x)$scDblFinder.score,
      "scDblFinder.clusters"=scDblFinder(x, clusters=TRUE)$scDblFinder.score,
      "scDblFinder.random"=scDblFinder(x, clusters=FALSE)$scDblFinder.score,
      "directDblClassification"=directDblClassification(x),
      "computeDoubletDensity"=computeDoubletDensity(x),
      "DoubletDetection"=DoubletCollection:::CallDoubletDetection(x),
      "Chord"=chordWrapper(x),
      DoubletCollection:::Callscds(count=x, method=method)
    )
}

scores <- lapply(datasets, FUN=function(x){
  x <- x[[1]]
  lapply(setNames(methods, methods), FUN=function(method){
    tryCatch({
      # average across 2 seeds:
      set.seed(42)
      st1 <- system.time( sco1 <- wrap(x, method) )
      set.seed(1234)
      st2 <- system.time( sco2 <- wrap(x, method) )
      list(scores=c(sco1+sco2)/2, time=(st1+st2)/2)
    }, error=function(e){
      warning("Error running ", method,":\n", e)
      list(scores=rep(NA_real_, ncol(x)), st=NA)
    })
  })
})
saveRDS(scores, file="scores.rds")
```

```{r}
scores <- readRDS("scores.rds")
true_labels <- lapply(datasets, FUN=function(x) as.integer(x[[2]]=='doublet'))

res <- dplyr::bind_rows(lapply(setNames(names(scores),names(scores)), 
                               FUN=function(ds){
  truth <- true_labels[[ds]]
  dplyr::bind_rows(lapply(scores[[ds]], FUN=function(x){
    s <- split(x$scores, truth)
    c(AUPRC=mean(as.numeric(PRROC::pr.curve(s[[2]], s[[1]])[2:3])),
      AUROC=PRROC::roc.curve(s[[2]], s[[1]])[[2]],
      elapsed=as.numeric(unlist(x$time["elapsed"])))
  }), .id="method")
}), .id="dataset")
saveRDS(as.data.frame(res), file="benchmark.results.rds")
```


```{r}
sessionInfo()
```

